# Generated by Django 5.2.16 on 2026-08-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("managed_services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("starter", "Başlangıç"),
                            ("verified", "Doğrulanmış Görev Ortağı"),
                            ("professional", "Profesyonel İlan Yöneticisi"),
                            ("authorized", "Yetkili Çözüm Ortağı"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Başvuru"),
                            ("active", "Aktif"),
                            ("suspended", "Askıda"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("about", models.TextField(blank=True, max_length=800)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("service_cities", models.JSONField(blank=True, default=list)),
                ("available", models.BooleanField(default=True)),
                ("identity_verified", models.BooleanField(default=False)),
                ("professional_documents_verified", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("completed_tasks", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("photo", "Fotoğraf / Video Çekimi"),
                            ("listing_prep", "İlan Hazırlama"),
                            ("price_research", "Fiyat Araştırması"),
                            ("message_management", "Mesaj Yönetimi"),
                            ("offer_collection", "Teklif Toplama"),
                            ("appointment", "Randevu Organizasyonu"),
                            ("showing", "Yerinde Gösterim"),
                            ("delivery", "Teslim Desteği"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=80)),
                ("district", models.CharField(max_length=80)),
                (
                    "min_level",
                    models.CharField(
                        choices=[
                            ("starter", "Başlangıç"),
                            ("verified", "Doğrulanmış Görev Ortağı"),
                            ("professional", "Profesyonel İlan Yöneticisi"),
                            ("authorized", "Yetkili Çözüm Ortağı"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("reward", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "success_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("assigned", "Atandı"),
                            ("in_progress", "Devam Ediyor"),
                            ("review", "Kontrolde"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("result_note", models.TextField(blank=True)),
                (
                    "proof_file",
                    models.FileField(blank=True, upload_to="task-proofs/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="partners.partnerprofile",
                    ),
                ),
                (
                    "managed_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="managed_services.managedrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PartnerEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("paid", "Ödendi"),
                            ("cancelled", "İptal"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="partners.partnerprofile",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earning",
                        to="partners.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TaskApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=700)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("accepted", "Kabul edildi"),
                            ("rejected", "Reddedildi"),
                            ("withdrawn", "Geri çekildi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_applications",
                        to="partners.partnerprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="partners.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "city", "task_type"],
                name="partners_ta_status_556870_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskapplication",
            constraint=models.UniqueConstraint(
                fields=("task", "partner"), name="unique_task_partner_application"
            ),
        ),
    ]
