# Generated by Django 5.2.16 on 2026-08-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountclosurerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_app_messages", models.BooleanField(default=True)),
                ("in_app_offers", models.BooleanField(default=True)),
                ("in_app_price_drops", models.BooleanField(default=True)),
                ("in_app_follows", models.BooleanField(default=True)),
                ("in_app_reviews", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=False)),
                ("email_offers", models.BooleanField(default=False)),
                ("email_transactions", models.BooleanField(default=False)),
                ("email_listing_updates", models.BooleanField(default=False)),
                ("email_price_drops", models.BooleanField(default=False)),
                ("email_follows", models.BooleanField(default=False)),
                ("email_reviews", models.BooleanField(default=False)),
                ("email_system", models.BooleanField(default=False)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("off", "Özet e-posta gönderme"),
                            ("daily", "Günlük özet"),
                            ("weekly", "Haftalık özet"),
                        ],
                        default="off",
                        max_length=12,
                    ),
                ),
                ("last_digest_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
