# Generated by Django 5.2.16 on 2026-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_matches",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="in_app_matches",
            field=models.BooleanField(default=True),
        ),
    ]
