# Generated by Django 5.2.16 on 2026-08-06 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notificationpreference_email_matches_and_more"),
        ("listings", "0007_listingimage_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fraud", "Dolandırıcılık şüphesi"),
                            ("fake_identity", "Sahte kimlik / yanıltıcı profil"),
                            ("harassment", "Taciz veya uygunsuz iletişim"),
                            ("spam", "Spam / sürekli istenmeyen iletişim"),
                            ("prohibited", "Yasaklı ürün veya faaliyet"),
                            ("other", "Diğer"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1600)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("reviewing", "İnceleniyor"),
                            ("resolved", "Çözüldü"),
                            ("dismissed", "İşlem gerektirmiyor"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reports",
                        to="listings.listing",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_user_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_user_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_user_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AccountRiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message", "Riskli mesaj"),
                            ("listing_report", "İlan şikâyeti"),
                            ("user_report", "Kullanıcı şikâyeti"),
                            ("duplicate_image", "Tekrarlanan fotoğraf"),
                            ("listing_content", "Şüpheli ilan içeriği"),
                            ("transaction", "İşlem uyuşmazlığı"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("critical", "Kritik"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("reviewing", "İnceleniyor"),
                            ("resolved", "Çözüldü"),
                            ("dismissed", "İşlem gerektirmiyor"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=96, unique=True)),
                ("summary", models.CharField(max_length=240)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_risk_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_risk_events",
                        to="listings.listing",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_risk_events",
                        to="listings.message",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_user_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events",
                        to="accounts.userreport",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(
                fields=["reported_user", "status", "-created_at"],
                name="accounts_us_reporte_227290_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(
                fields=["reporter", "-created_at"],
                name="accounts_us_reporte_360f26_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reporter", models.F("reported_user")), _negated=True
                ),
                name="prevent_self_user_report",
            ),
        ),
        migrations.AddIndex(
            model_name="accountriskevent",
            index=models.Index(
                fields=["subject_user", "status", "-created_at"],
                name="accounts_ac_subject_2c52ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountriskevent",
            index=models.Index(
                fields=["severity", "status", "-created_at"],
                name="accounts_ac_severit_62c7f7_idx",
            ),
        ),
    ]
