# Generated by Django 5.2.16 on 2026-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userreport_accountriskevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_phone_calls",
            field=models.BooleanField(
                default=False, verbose_name="İlanlarımda telefonla aranmak istiyorum"
            ),
        ),
    ]
