# Generated by Django 5.2.16 on 2026-08-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("digital", "Dijital Asistan"),
                            ("on_site", "Yerinde Destek"),
                            ("full", "Tam Yönetim"),
                        ],
                        default="digital",
                        max_length=20,
                    ),
                ),
                ("requested_services", models.JSONField(blank=True, default=list)),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Telefon"),
                            ("message", "İlan Şehri mesajı"),
                            ("email", "E-posta"),
                        ],
                        default="message",
                        max_length=16,
                    ),
                ),
                (
                    "quote_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "success_fee_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("next_action", models.CharField(blank=True, max_length=240)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yeni talep"),
                            ("review", "İhtiyaç analizi"),
                            ("quoted", "Teklif sunuldu"),
                            ("active", "Aktif yönetim"),
                            ("waiting_customer", "Müşteri bekleniyor"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_managed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_request",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ManagedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("note", "Not"),
                            ("call", "Telefon görüşmesi"),
                            ("photo", "Fotoğraf / video"),
                            ("price", "Fiyat araştırması"),
                            ("message", "Mesaj / teklif yönetimi"),
                            ("appointment", "Randevu"),
                            ("status", "Durum güncellemesi"),
                        ],
                        default="note",
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(max_length=1600)),
                ("visible_to_customer", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="managed_services.managedrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tam yönetim aktiviteleri",
                "ordering": ("-created_at",),
            },
        ),
    ]
