from django.urls import path

from .views import (
    CompareListView,
    ConversationDetailView,
    ConversationListView,
    FavoriteListView,
    ListingCreateView,
    ListingDeleteView,
    ListingDetailView,
    ListingListView,
    ListingUpdateView,
    ModerationDashboardView,
    NotificationListView,
    OfferCenterView,
    TransactionDetailView,
    archive_conversation,
    change_listing_status,
    counter_offer_action,
    create_review,
    delete_listing_image,
    delete_saved_search,
    location_suggestions,
    mark_all_notifications_read,
    mark_notification_read,
    moderate_listing,
    moderate_report,
    moderate_transaction,
    offer_action,
    reorder_listing_images,
    report_listing,
    save_search,
    set_cover_image,
    start_conversation,
    toggle_compare,
    toggle_favorite,
    transaction_action,
)

app_name = "listings"

urlpatterns = [
    path("", ListingListView.as_view(), name="list"),
    path("yeni/", ListingCreateView.as_view(), name="create"),
    path("favorilerim/", FavoriteListView.as_view(), name="favorites"),
    path("karsilastir/", CompareListView.as_view(), name="compare"),
    path("aramalar/kaydet/", save_search, name="save_search"),
    path("aramalar/<int:pk>/sil/", delete_saved_search, name="delete_saved_search"),
    path("mesajlar/", ConversationListView.as_view(), name="conversation_list"),
    path("mesajlar/<int:pk>/", ConversationDetailView.as_view(), name="conversation_detail"),
    path("mesajlar/<int:pk>/arsivle/", archive_conversation, name="archive_conversation"),
    path("bildirimler/", NotificationListView.as_view(), name="notifications"),
    path("bildirimler/tumunu-oku/", mark_all_notifications_read, name="mark_all_notifications_read"),
    path("bildirimler/<int:pk>/oku/", mark_notification_read, name="mark_notification_read"),
    path("tekliflerim/", OfferCenterView.as_view(), name="offer_center"),
    path("teklif/<int:pk>/karsi-teklif/", counter_offer_action, name="counter_offer"),
    path("teklif/<int:pk>/<str:action>/", offer_action, name="offer_action"),
    path("islem/<uuid:public_id>/", TransactionDetailView.as_view(), name="transaction_detail"),
    path("islem/<uuid:public_id>/degerlendir/", create_review, name="create_review"),
    path("islem/<uuid:public_id>/<str:action>/", transaction_action, name="transaction_action"),
    path("moderasyon/", ModerationDashboardView.as_view(), name="moderation"),
    path("moderasyon/ilan/<int:pk>/<str:action>/", moderate_listing, name="moderate_listing"),
    path("moderasyon/sikayet/<int:pk>/<str:action>/", moderate_report, name="moderate_report"),
    path("moderasyon/islem/<uuid:public_id>/<str:action>/", moderate_transaction, name="moderate_transaction"),
    path("konum-onerileri/", location_suggestions, name="location_suggestions"),
    path("<slug:slug>/duzenle/", ListingUpdateView.as_view(), name="update"),
    path("<slug:slug>/sil/", ListingDeleteView.as_view(), name="delete"),
    path("<slug:slug>/durum/<str:action>/", change_listing_status, name="change_status"),
    path("<slug:slug>/favori/", toggle_favorite, name="toggle_favorite"),
    path("<slug:slug>/karsilastir/", toggle_compare, name="toggle_compare"),
    path("<slug:slug>/mesaj-gonder/", start_conversation, name="start_conversation"),
    path("<slug:slug>/sikayet/", report_listing, name="report"),
    path("<slug:slug>/fotograf/<int:image_id>/kapak/", set_cover_image, name="set_cover_image"),
    path("<slug:slug>/fotograf/<int:image_id>/sil/", delete_listing_image, name="delete_image"),
    path("<slug:slug>/fotograflar/sirala/", reorder_listing_images, name="reorder_images"),
    path("<slug:slug>/", ListingDetailView.as_view(), name="detail"),
]
