# Generated by Django 5.2.16 on 2026-08-04 14:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="listings.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kategoriler",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("product", "Ürün / Eşya"),
                            ("vehicle", "Araç"),
                            ("real_estate", "Emlak"),
                            ("service", "Hizmet"),
                            ("need", "İhtiyaç / Arıyorum"),
                            ("job", "İş"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sell", "Satılık"),
                            ("rent", "Kiralık"),
                            ("swap", "Takas"),
                            ("wanted", "Arıyorum"),
                            ("service_offer", "Hizmet Veriyorum"),
                            ("service_request", "Hizmet Arıyorum"),
                            ("job_offer", "Çalışan Arıyorum"),
                            ("job_request", "İş Arıyorum"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "management_mode",
                    models.CharField(
                        choices=[
                            ("self", "Kendim yöneteceğim"),
                            ("full", "İlan Şehri yönetsin"),
                        ],
                        default="self",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=210, unique=True)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("price_on_request", models.BooleanField(default=False)),
                ("is_negotiable", models.BooleanField(default=False)),
                (
                    "delivery_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("handover", "Elden teslim"),
                            ("shipping", "Kargo"),
                            ("on_site", "Yerinde hizmet / teslim"),
                            ("digital", "Dijital teslim"),
                            ("negotiable", "Görüşülür"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("model_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gasoline", "Benzin"),
                            ("diesel", "Dizel"),
                            ("lpg", "LPG"),
                            ("hybrid", "Hibrit"),
                            ("electric", "Elektrik"),
                            ("other", "Diğer"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatic", "Otomatik"),
                            ("manual", "Manuel"),
                            ("semi_automatic", "Yarı otomatik"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("room_count", models.CharField(blank=True, default="", max_length=30)),
                ("area_m2", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "building_age",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "floor_location",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "heating_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "service_area",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "fee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Sabit ücret"),
                            ("hourly", "Saatlik"),
                            ("daily", "Günlük"),
                            ("monthly", "Aylık"),
                            ("negotiable", "Görüşülür"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Tam zamanlı"),
                            ("part_time", "Yarı zamanlı"),
                            ("daily", "Günlük / dönemsel"),
                            ("remote", "Uzaktan"),
                            ("internship", "Staj"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("city", models.CharField(max_length=80)),
                ("district", models.CharField(max_length=80)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("review", "İncelemede"),
                            ("published", "Yayında"),
                            ("paused", "Duraklatıldı"),
                            ("completed", "Sonuçlandı"),
                            ("rejected", "Reddedildi"),
                            ("expired", "Süresi doldu"),
                        ],
                        default="review",
                        max_length=16,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("renewal_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="listings.category",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-is_featured", "-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_archived", models.BooleanField(default=False)),
                ("seller_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buying_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selling_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ListingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fraud", "Dolandırıcılık şüphesi"),
                            ("wrong_info", "Yanlış / yanıltıcı bilgi"),
                            ("prohibited", "Yasaklı ürün veya hizmet"),
                            ("duplicate", "Tekrarlanan ilan"),
                            ("harassment", "Uygunsuz iletişim"),
                            ("other", "Diğer"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açık"),
                            ("reviewing", "İnceleniyor"),
                            ("resolved", "Çözüldü"),
                            ("dismissed", "İşlem gerektirmiyor"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="listings.listing",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_listing_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1600)),
                (
                    "attachment",
                    models.ImageField(blank=True, upload_to="messages/%Y/%m/"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="listings.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_listing_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Mesaj"),
                            ("offer", "Teklif"),
                            ("transaction", "İşlem"),
                            ("review", "Puan / yorum"),
                            ("listing_status", "İlan durumu"),
                            ("managed", "Tam yönetim"),
                            ("task", "Görev"),
                            ("verification", "Doğrulama"),
                            ("system", "Sistem"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.CharField(blank=True, max_length=320)),
                ("link", models.CharField(blank=True, max_length=320)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("message", models.TextField(max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("accepted", "Kabul edildi"),
                            ("rejected", "Reddedildi"),
                            ("withdrawn", "Geri çekildi"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="listings.listing",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("query_params", models.JSONField(default=dict)),
                ("alert_enabled", models.BooleanField(default=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agreed", "Anlaşma sağlandı"),
                            ("delivery", "Teslim / hizmet aşamasında"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal edildi"),
                            ("disputed", "Uyuşmazlık bildirildi"),
                        ],
                        default="agreed",
                        max_length=16,
                    ),
                ),
                ("buyer_confirmed", models.BooleanField(default=False)),
                ("seller_confirmed", models.BooleanField(default=False)),
                ("dispute_reason", models.TextField(blank=True, max_length=1500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="listings.listing",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction",
                        to="listings.offer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="listings.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "kind", "action"],
                name="listings_li_status_5ea90c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["city", "district"], name="listings_li_city_885438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["brand", "model_name"], name="listings_li_brand_9f1be8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-created_at"], name="listings_li_created_92fa22_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_user_listing_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("listing", "buyer"), name="unique_listing_buyer_conversation"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.UniqueConstraint(
                fields=("listing", "reporter"), name="unique_listing_reporter"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read", "created_at"],
                name="listings_me_convers_0e5f95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="listings_no_user_id_89e36b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["listing", "status", "-created_at"],
                name="listings_of_listing_d9af84_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("transaction", "reviewer"), name="unique_transaction_reviewer"
            ),
        ),
    ]
