# Generated by Django 5.2.16 on 2026-08-04 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="counter_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="offer",
            name="last_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_acted_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Mesaj"),
                    ("offer", "Teklif"),
                    ("transaction", "İşlem"),
                    ("review", "Puan / yorum"),
                    ("listing_status", "İlan durumu"),
                    ("managed", "Tam yönetim"),
                    ("task", "Görev"),
                    ("verification", "Doğrulama"),
                    ("price_drop", "Fiyat düşüşü"),
                    ("follow", "Satıcı takibi"),
                    ("system", "Sistem"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ListingPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notifications_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_price_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["listing", "-created_at"],
                        name="listings_li_listing_1440bb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfferEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Teklif gönderildi"),
                            ("countered", "Karşı teklif gönderildi"),
                            ("accepted", "Teklif kabul edildi"),
                            ("rejected", "Teklif reddedildi"),
                            ("withdrawn", "Teklif geri çekildi"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=1200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="listings.offer",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["offer", "created_at"],
                        name="listings_of_offer_i_d052a1_idx",
                    )
                ],
            },
        ),
    ]
