# Generated by Django 5.2.16 on 2026-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listingdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="color",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="listing",
            name="search_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="listing",
            name="technical_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
