# Generated by Django 5.2.16 on 2026-08-06 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_color_listing_search_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Mesaj"),
                    ("offer", "Teklif"),
                    ("transaction", "İşlem"),
                    ("review", "Puan / yorum"),
                    ("listing_status", "İlan durumu"),
                    ("managed", "Tam yönetim"),
                    ("task", "Görev"),
                    ("verification", "Doğrulama"),
                    ("price_drop", "Fiyat düşüşü"),
                    ("follow", "Satıcı takibi"),
                    ("match", "Akıllı eşleşme"),
                    ("system", "Sistem"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ListingMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "wanted_status",
                    models.CharField(
                        choices=[
                            ("new", "Yeni"),
                            ("viewed", "Görüldü"),
                            ("dismissed", "Gizlendi"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "offered_status",
                    models.CharField(
                        choices=[
                            ("new", "Yeni"),
                            ("viewed", "Görüldü"),
                            ("dismissed", "Gizlendi"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("notified_wanted_at", models.DateTimeField(blank=True, null=True)),
                ("notified_offered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offered_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_matches",
                        to="listings.listing",
                    ),
                ),
                (
                    "wanted_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_matches",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlan Eşleşmesi",
                "verbose_name_plural": "İlan Eşleşmeleri",
                "ordering": ("-score", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["wanted_listing", "wanted_status", "-score"],
                        name="listings_li_wanted__4b9925_idx",
                    ),
                    models.Index(
                        fields=["offered_listing", "offered_status", "-score"],
                        name="listings_li_offered_e1e63c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wanted_listing", "offered_listing"),
                        name="unique_wanted_offered_listing_match",
                    )
                ],
            },
        ),
    ]
