# Generated by Django 5.2.16 on 2026-08-06 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_notification_notification_type_listingmatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearchMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="alert_frequency",
            field=models.CharField(
                choices=[
                    ("off", "Kapalı"),
                    ("instant", "Anlık"),
                    ("daily", "Günlük özet"),
                ],
                default="instant",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Mesaj"),
                    ("offer", "Teklif"),
                    ("transaction", "İşlem"),
                    ("review", "Puan / yorum"),
                    ("listing_status", "İlan durumu"),
                    ("managed", "Tam yönetim"),
                    ("task", "Görev"),
                    ("verification", "Doğrulama"),
                    ("price_drop", "Fiyat düşüşü"),
                    ("follow", "Satıcı takibi"),
                    ("match", "Akıllı eşleşme"),
                    ("search_alert", "Kayıtlı arama"),
                    ("system", "Sistem"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(
                fields=["alert_enabled", "alert_frequency", "last_checked_at"],
                name="listings_sa_alert_e_580b2f_idx",
            ),
        ),
        migrations.AddField(
            model_name="savedsearchmatch",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_search_matches",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="savedsearchmatch",
            name="saved_search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="listings.savedsearch",
            ),
        ),
        migrations.AddIndex(
            model_name="savedsearchmatch",
            index=models.Index(
                fields=["saved_search", "notified_at", "-created_at"],
                name="listings_sa_saved_s_0c1617_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedsearchmatch",
            constraint=models.UniqueConstraint(
                fields=("saved_search", "listing"),
                name="unique_saved_search_listing_match",
            ),
        ),
    ]
