# Generated by Django 5.2.16 on 2026-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_savedsearchmatch_savedsearch_alert_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingimage",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
