# Generated by Django 5.2.16 on 2026-08-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listingimage_fingerprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "İşlem oluşturuldu"),
                            ("delivery_started", "Teslim aşaması başladı"),
                            ("code_created", "Teslim kodu oluşturuldu"),
                            ("handover_verified", "Teslim kodu doğrulandı"),
                            ("buyer_confirmed", "Alıcı tamamlamayı onayladı"),
                            ("seller_confirmed", "Satıcı tamamlamayı onayladı"),
                            ("completed", "İşlem tamamlandı"),
                            ("cancelled", "İşlem iptal edildi"),
                            ("disputed", "Uyuşmazlık açıldı"),
                            ("moderated", "Destek ekibi sonuçlandırdı"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="review",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="buyer_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="delivery_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("handover", "Elden teslim"),
                    ("shipping", "Kargo"),
                    ("on_site", "Yerinde hizmet / teslim"),
                    ("digital", "Dijital teslim"),
                    ("negotiable", "Görüşülür"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="handover_code_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="handover_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="handover_code_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="transaction",
            name="handover_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="seller_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewer", models.F("reviewed_user")), _negated=True
                ),
                name="prevent_self_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("buyer", models.F("seller")), _negated=True),
                name="prevent_self_transaction",
            ),
        ),
        migrations.AddField(
            model_name="transactionevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionevent",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="listings.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionevent",
            index=models.Index(
                fields=["transaction", "created_at"],
                name="listings_tr_transac_c76639_idx",
            ),
        ),
    ]
