# Generated by Django 5.2.16 on 2026-08-06 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_transactionevent_review_published_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("in_person", "Yüz yüze görüşme"),
                            ("phone", "Telefon görüşmesi"),
                            ("video", "Görüntülü görüşme"),
                            ("delivery", "Teslim / hizmet randevusu"),
                        ],
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("district", models.CharField(blank=True, max_length=80)),
                ("place", models.CharField(blank=True, max_length=180)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Yanıt bekliyor"),
                            ("accepted", "Onaylandı"),
                            ("declined", "Reddedildi"),
                            ("cancelled", "İptal edildi"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="listings.conversation",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="listings.listing",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "starts_at"],
                        name="listings_ap_status_4f2e9a_idx",
                    ),
                    models.Index(
                        fields=["invitee", "status", "starts_at"],
                        name="listings_ap_invitee_ef1ebb_idx",
                    ),
                    models.Index(
                        fields=["proposer", "status", "starts_at"],
                        name="listings_ap_propose_dd577c_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("proposer", models.F("invitee")), _negated=True
                        ),
                        name="prevent_self_appointment",
                    )
                ],
            },
        ),
    ]
