# Generated by Django 5.2.16 on 2026-08-04 18:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_listingdraft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("processing", "İşleniyor"),
                            ("succeeded", "Başarılı"),
                            ("failed", "Başarısız"),
                            ("blocked", "Güvenlik nedeniyle engellendi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "safety_status",
                    models.CharField(
                        choices=[
                            ("safe", "Güvenli"),
                            ("review_required", "Kullanıcı onayı gerekli"),
                            ("blocked", "Engellendi"),
                        ],
                        default="review_required",
                        max_length=24,
                    ),
                ),
                ("provider", models.CharField(max_length=24)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(max_length=80)),
                ("request_hash", models.CharField(blank=True, max_length=64)),
                ("image_count", models.PositiveSmallIntegerField(default=0)),
                ("image_fingerprints", models.JSONField(blank=True, default=list)),
                ("validated_output", models.JSONField(blank=True, default=dict)),
                ("confidence_score", models.PositiveSmallIntegerField(default=0)),
                ("safety_warnings", models.JSONField(blank=True, default=list)),
                ("missing_questions", models.JSONField(blank=True, default=list)),
                ("form_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("provider_request_id", models.CharField(blank=True, max_length=160)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analyses",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_listing_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yapay Zekâ Analizi",
                "verbose_name_plural": "Yapay Zekâ Analizleri",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIFieldChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=80)),
                ("suggested_value", models.JSONField(blank=True, null=True)),
                ("final_value", models.JSONField(blank=True, null=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("accepted", "Öneri aynen kabul edildi"),
                            ("edited", "Kullanıcı düzenledi"),
                            ("cleared", "Kullanıcı temizledi"),
                            ("not_applied", "Forma uygulanmadı"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_changes",
                        to="ai_listing.aianalysis",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_field_changes",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yapay Zekâ Alan Değişikliği",
                "verbose_name_plural": "Yapay Zekâ Alan Değişiklikleri",
                "ordering": ("field_name",),
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="Özellik açık"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "Test sağlayıcısı"),
                            ("http_json", "Harici JSON görsel servisi"),
                        ],
                        default="mock",
                        max_length=24,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="vision-model", max_length=120
                    ),
                ),
                (
                    "user_daily_limit",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Kullanıcı başına günlük limit",
                    ),
                ),
                (
                    "site_daily_limit",
                    models.PositiveIntegerField(
                        default=250,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="Site geneli günlük limit",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=45,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "max_images",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "max_image_size_mb",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "min_confidence_score",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "successful_analyses",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "failed_analyses",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "blocked_analyses",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "total_duration_ms",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "last_connection_checked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_connection_ok",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "last_connection_message",
                    models.CharField(blank=True, editable=False, max_length=500),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ai_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yapay Zekâ Ayarı",
                "verbose_name_plural": "Yapay Zekâ Ayarları",
            },
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_listing__user_id_99167b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["status", "-created_at"], name="ai_listing__status_f1b140_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["safety_status", "-created_at"],
                name="ai_listing__safety__dbb86f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aianalysis",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"),
                name="unique_ai_analysis_idempotency_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="aifieldchange",
            index=models.Index(
                fields=["analysis", "field_name"], name="ai_listing__analysi_a70d91_idx"
            ),
        ),
    ]
