# Generated by Django 5.2.16 on 2026-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="model_name",
            field=models.CharField(
                blank=True, default="gemini-3.6-flash", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="provider",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini görsel analizi"),
                    ("mock", "Test sağlayıcısı"),
                    ("openai", "OpenAI görsel analizi (yedek)"),
                    ("http_json", "Harici JSON görsel servisi"),
                ],
                default="gemini",
                max_length=24,
            ),
        ),
    ]
